In [1]:
import numpy as np

In [4]:
arr = np.array([[1,2,3], [4,5,6]])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a1 = np.array([1,2,3,4,5])

In [9]:
a1

array([1, 2, 3, 4, 5])

# Attributes 

In [13]:
a1.shape

(5,)

In [14]:
arr.shape

(2, 3)

In [15]:
a1.ndim

1

In [17]:
arr.ndim

2

In [18]:
a1.dtype, arr.dtype

(dtype('int64'), dtype('int64'))

In [19]:
a1.size, arr.size

(5, 6)

In [20]:
type(a1), type(arr)

(numpy.ndarray, numpy.ndarray)

# Methods in numpy

In [22]:
# create a dataframe from numpy
import pandas as pd

In [23]:
df = pd.DataFrame(arr)
df

0  1  2
0  1  2  3
1  4  5  6

# create numpy arrays


In [24]:
sample_array = np.array(list(range(1,4)))

In [25]:
sample_array

array([1, 2, 3])

In [29]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
zeros = np.zeros((5,))
zeros

array([0., 0., 0., 0., 0.])

In [31]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [34]:
random_array = np.random.randint(1,6, size=(2,3))
random_array

array([[1, 3, 5],
       [3, 2, 3]])

In [42]:
a2 = np.random.random((2,3))
a2

array([[0.13530096, 0.32252192, 0.80433906],
       [0.44339154, 0.12541079, 0.76510257]])

## Random Seed

In [40]:
# pseudo-random numbers
# np.random.seed()

In [54]:
np.random.seed(seed = 0)
random_arr = np.random.randint(10, size=(5,3))

In [57]:
random_arr

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [60]:
np.random.seed(4)
rand_arr_5 = np.random.random((5,3))
rand_arr_5

array([[0.96702984, 0.54723225, 0.97268436],
       [0.71481599, 0.69772882, 0.2160895 ],
       [0.97627445, 0.00623026, 0.25298236],
       [0.43479153, 0.77938292, 0.19768507],
       [0.86299324, 0.98340068, 0.16384224]])

## Viewing Arrays and Matrices

In [63]:
np.unique(np.array([1,2,3,4,3,2,1,4]))

array([1, 2, 3, 4])

In [64]:
np.unique(random_arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
a1

array([1, 2, 3, 4, 5])

In [66]:
a2

array([[0.13530096, 0.32252192, 0.80433906],
       [0.44339154, 0.12541079, 0.76510257]])

In [68]:
a2[0]

array([0.13530096, 0.32252192, 0.80433906])

In [69]:
a2[0][2]

0.8043390627991102

In [70]:
a2.shape

(2, 3)

In [85]:
a3 = np.random.randint(10, size=(2,3,3))

In [86]:
a3

array([[[1, 9, 9],
        [0, 7, 2],
        [6, 3, 7]],

       [[8, 2, 6],
        [7, 7, 9],
        [2, 7, 5]]])

In [87]:
a3[0]

array([[1, 9, 9],
       [0, 7, 2],
       [6, 3, 7]])

In [89]:
a3[1]

array([[8, 2, 6],
       [7, 7, 9],
       [2, 7, 5]])

In [90]:
a1

array([1, 2, 3, 4, 5])

In [91]:
a2

array([[0.13530096, 0.32252192, 0.80433906],
       [0.44339154, 0.12541079, 0.76510257]])

In [92]:
a3

array([[[1, 9, 9],
        [0, 7, 2],
        [6, 3, 7]],

       [[8, 2, 6],
        [7, 7, 9],
        [2, 7, 5]]])

In [93]:
a3[:2,:2,:2]

array([[[1, 9],
        [0, 7]],

       [[8, 2],
        [7, 7]]])

In [84]:
a3.shape

(2, 3, 4)

In [94]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[3, 0, 5, 4, 3],
         [8, 9, 5, 8, 6],
         [7, 0, 4, 6, 8],
         [4, 8, 1, 9, 5]],

        [[4, 2, 3, 4, 7],
         [6, 6, 8, 0, 3],
         [5, 6, 1, 1, 6],
         [0, 8, 7, 5, 7]],

        [[6, 8, 4, 4, 0],
         [7, 2, 1, 8, 8],
         [1, 3, 1, 3, 6],
         [7, 4, 0, 7, 3]]],


       [[[7, 9, 6, 6, 9],
         [3, 2, 7, 6, 7],
         [9, 4, 3, 0, 5],
         [0, 9, 5, 7, 5]],

        [[9, 8, 2, 4, 2],
         [3, 0, 3, 6, 9],
         [0, 3, 4, 8, 6],
         [3, 7, 3, 9, 1]],

        [[4, 8, 3, 0, 2],
         [4, 6, 1, 9, 0],
         [9, 3, 1, 2, 3],
         [2, 9, 5, 2, 7]]]])

In [95]:
a4.shape

(2, 3, 4, 5)

In [96]:
# Get first four numbers of the innermost array
a4[:,:,:,:4]

array([[[[3, 0, 5, 4],
         [8, 9, 5, 8],
         [7, 0, 4, 6],
         [4, 8, 1, 9]],

        [[4, 2, 3, 4],
         [6, 6, 8, 0],
         [5, 6, 1, 1],
         [0, 8, 7, 5]],

        [[6, 8, 4, 4],
         [7, 2, 1, 8],
         [1, 3, 1, 3],
         [7, 4, 0, 7]]],


       [[[7, 9, 6, 6],
         [3, 2, 7, 6],
         [9, 4, 3, 0],
         [0, 9, 5, 7]],

        [[9, 8, 2, 4],
         [3, 0, 3, 6],
         [0, 3, 4, 8],
         [3, 7, 3, 9]],

        [[4, 8, 3, 0],
         [4, 6, 1, 9],
         [9, 3, 1, 2],
         [2, 9, 5, 2]]]])

In [98]:
a4[:,:,:,:1]

array([[[[3],
         [8],
         [7],
         [4]],

        [[4],
         [6],
         [5],
         [0]],

        [[6],
         [7],
         [1],
         [7]]],


       [[[7],
         [3],
         [9],
         [0]],

        [[9],
         [3],
         [0],
         [3]],

        [[4],
         [4],
         [9],
         [2]]]])

In [99]:
a3

array([[[1, 9, 9],
        [0, 7, 2],
        [6, 3, 7]],

       [[8, 2, 6],
        [7, 7, 9],
        [2, 7, 5]]])

In [100]:
a3.shape

(2, 3, 3)

In [113]:
a3[:,:,-2:-1]

array([[[9],
        [7],
        [3]],

       [[2],
        [7],
        [7]]])

# Arithmetic

In [114]:
a1 = np.ones(3)

In [115]:
a1

array([1., 1., 1.])

In [116]:
a1 + 1

array([2., 2., 2.])

In [118]:
a2 = np.array([2,3,4])

In [119]:
a1 + a2

array([3., 4., 5.])

In [120]:
a1 - a2

array([-1., -2., -3.])

In [121]:
a1 * a2

array([2., 3., 4.])

In [123]:
a1 / a2

array([0.5       , 0.33333333, 0.25      ])

In [124]:
a1 // a2

array([0., 0., 0.])

In [125]:
a2 ** a2

array([  4,  27, 256])

In [126]:
a2 ** a1

array([2., 3., 4.])

In [128]:
a3 = np.array((3,2))


In [130]:
a2.shape


(3,)

In [131]:
a3.shape

(2,)

In [134]:
# a3 * a2
massive_arr = np.random.random(10000)

In [135]:
massive_arr.shape

(10000,)

In [137]:
massive_arr[:10]


array([0.49996145, 0.40963549, 0.81083712, 0.51577168, 0.48968914,
       0.87039214, 0.89809177, 0.1391818 , 0.72955459, 0.56534436])

In [140]:
%timeit sum(massive_arr) # Python sum method

1.61 ms ± 59.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [141]:
%timeit np.sum(massive_arr) # np sum method

7.43 µs ± 57.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [142]:
a2

array([2, 3, 4])

In [143]:
a3

array([3, 2])

In [145]:
a3 = np.array((3,2))

In [147]:
a3.mean()

2.5

In [148]:
a3

array([3, 2])

## Nut Butter sales example

In [5]:
import numpy as np
import pandas as pd
np.random.seed(1)
# number of jars sold
sales_amount = np.random.randint(20, size=(5, 3))
sales_amount

array([[ 5, 11, 12],
       [ 8,  9, 11],
       [ 5, 15,  0],
       [16,  1, 12],
       [ 7, 13,  6]])

In [7]:
weekely_sales_amount = pd.DataFrame(sales_amount, index=['Mon', 'Tues', 'Wed', 'Thu', 'Fri'], 
                                    columns=['Almond Butter', 'Peanut Butter', 'Cashew Butter'])
weekely_sales_amount

Almond Butter  Peanut Butter  Cashew Butter
Mon               5             11             12
Tues              8              9             11
Wed               5             15              0
Thu              16              1             12
Fri               7             13              6

In [8]:
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [11]:
# create butter prices dataframe
butter_prices = pd.DataFrame(prices.reshape(1,3), index=['Price'], 
                            columns=['Almond Butter', 'Peanut Butter', 'Cashew Butter'])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [13]:
total_sales = prices.dot(sales_amount)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [15]:
total_sales = prices.dot(sales_amount.T)
total_sales

array([282, 284, 170, 312, 246])

In [21]:
weekely_sales_amount['Total ($)'] = total_sales

In [23]:
weekely_sales_amount.drop(['Total Sales'], axis=1, inplace=True)

In [24]:
weekely_sales_amount

Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon               5             11             12        282
Tues              8              9             11        284
Wed               5             15              0        170
Thu              16              1             12        312
Fri               7             13              6        246

In [25]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

## Manipulating and Comparing Array
## Comparison Operator

In [26]:
a1 = np.array([1,2,3])
a2 = np.array([[1,2,3], [4,5,6.5]])

In [27]:
a1

array([1, 2, 3])

In [28]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [29]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [30]:
a2 > a1

array([[False, False, False],
       [ True,  True,  True]])

In [31]:
a1 == a2

array([[ True,  True,  True],
       [False, False, False]])

## Sorting Arrays

In [33]:
random_arr = np.random.randint(10, size=(3,4))

In [34]:
random_arr

array([[9, 2, 4, 5],
       [2, 4, 2, 4],
       [7, 7, 9, 1]])

In [35]:
random_arr.shape

(3, 4)

In [36]:
np.sort(random_arr)

array([[2, 4, 5, 9],
       [2, 2, 4, 4],
       [1, 7, 7, 9]])

In [37]:
np.argsort(random_arr)

array([[1, 2, 3, 0],
       [0, 2, 1, 3],
       [3, 0, 1, 2]])

## Practical Example of numpy 

In [42]:
<img src="images/panda.png"/>

SyntaxError: invalid syntax (<ipython-input-42-5ad02dd7b21a>, line 1)

In [43]:
ls

images/  numpy-practice.ipynb


In [44]:
cd images

/home/ashish/ml-projects/numpy-practice/images


In [45]:
pwd

'/home/ashish/ml-projects/numpy-practice/images'

In [46]:
<img src="panda.png"/>

SyntaxError: invalid syntax (<ipython-input-46-2ffd334afd26>, line 1)

In [47]:
ls

car-photo.png*  dog-photo.png*  panda.png*


In [48]:
cd .

/home/ashish/ml-projects/numpy-practice/images


In [49]:
cd ..

/home/ashish/ml-projects/numpy-practice


In [50]:
ls

images/  numpy-practice.ipynb


<img src="images/panda.png"/>

In [53]:
import numpy as np
from matplotlib.image import imread


In [54]:
panda = imread("images/panda.png", format=None)
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [55]:
panda.shape

(2330, 3500, 3)

In [56]:
type(panda)

numpy.ndarray

In [57]:
panda.size

24465000

In [58]:
panda.ndim

3

In [59]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

In [60]:
ls

images/  numpy-practice.ipynb


In [61]:
car = imread("images/car-photo.png")

In [62]:
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [63]:
car.size, car.shape, car.ndim

(991300, (431, 575, 4), 3)

In [64]:
dog = imread("images/dog-photo.png")

In [65]:
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274